export const randomUsers = [
    "Anna", "Jonas", "Kari", "Mats", "Ole", "Liv", "Erik", "Sofia", 
    "Lars", "Maria", "Henrik", "Ingrid", "Anders", "Nina", "Thomas",
    "Kristin", "Johan", "Astrid", "Petter", "Silje", "Arne", "Heidi"
  ];
  
  export const randomChatMessages = [
    "Dette er fantastisk!",
    "Elsker denne sendingen så langt!",
    "Hilsen fra Oslo!",
    "Når kommer neste sending?",
    "Første gang jeg ser, dette er flott!",
    "Hei fra Bergen!",
    "Kan noen forklare hva som nettopp skjedde?",
    "Kvaliteten på denne sendingen er utrolig",
    "Jeg har ventet på dette hele uken!",
    "Er det noen som vet hvilken sang som spilles?",
    "Wow, det var uventet!",
    "Hilsen fra Trondheim!",
    "Programlederen gjør en fantastisk jobb",
    "Jeg kan ikke tro hva jeg nettopp så",
    "Dette er bedre enn forrige ukes sending",
    "Noen nyheter om kommende arrangementer?",
    "Dette minner meg om sendingen forrige måned",
    "Jeg må dele dette med vennene mine",
    "Lyseffektene er utrolige",
    "Hvem andre ser på fra Stavanger?",
    "Jeg koser meg skikkelig med denne sendingen!",
    "Er det noen som vet når neste episode kommer?",
    "Dette må være det beste jeg har sett i år",
    "For en fantastisk produksjon",
    "Tusen takk for strålende underholdning",
    "Det er så spennende nå!",
    "Lurer på hva som skjer videre",
    "Er det noen som har sett på tidligere episoder?",
    "Jeg elsker dette!",
    "Er det noen som kan anbefale lignende programmer?",
    "Jeg er så glad for at jeg rakk denne sendingen",
    "Dette er grunnen til at jeg elsker NRK",
    "Er det noen som vet hvor jeg kan se tidligere episoder?",
    "Jeg elsker å se på dette med familien",
    "lol dette suger",
    "Hvordan kan folk like dette?",
    "Jeg er så lei av denne typen programmering",
    "Hvorfor er dette på TV?",
    "Jeg kan ikke tro at folk betaler for dette",
    "Dette er så kjedelig",
    "Jeg forstår ikke hvorfor dette er populært",
    "Er det noen som faktisk liker dette?",
    "Jeg har sett bedre ting på YouTube",
    "Jeg kan ikke tro at jeg brukte tid på dette",
    "Dette er så overhypet",
    "Jeg ville aldri anbefalt dette til noen",
    "Hvorfor er dette fortsatt på lufta?",
    "Ser dette med mamma og pappa",
    "d r akkurat sånn det er legit",
    "WTF",
    "😭😭😭",
    "😭😭",
    "😭",
    "😡😡😡",
    "😡😡",
    "😡",
    "😂😂😂",
    "😂😂",
    "😂",
    "😱",
    "😅",
    
  ];
  
  export const randomComments = [
    "Flott dekning!",
    "NRK leverer alltid 💙",
    "Gleder meg til mer innhold som dette",
    "Dette er grunnen til at jeg betaler lisensen min!",
    "Produksjonsverdien er utrolig",
    "Deler dette med familien min",
    "Beste sendingen jeg har sett på lenge",
    "Helt fantastisk sending",
    "Ser frem til neste episode",
    "NRK setter standarden som vanlig",
    "Utrolig arbeid av teamet",
    "Jeg har fulgt med siden begynnelsen",
    "Dette er høykvalitets-programmering",
    "Alltid imponert over NRKs innhold",
    "Dette fortjener flere seere!",
    "Takk for at dere gjør dette tilgjengelig online",
    "Programlederen er så engasjerende",
    "Skuffer aldri 👏",
    "Jeg lærer så mye av dette",
    "Vær så snill å lage flere slike sendinger!",
    "Utrolig bra lydkvalitet i dag",
    "Dette er grunnen til at NRK er best",
    "Nydelig fotografering i denne sendingen",
    "Elsker den nye formatet",
    "Når kommer dette på NRK TV?"
  ];
  
  export const initialChatMessages = [
    { user: "Anna", message: "Dette er fantastisk!" },
    { user: "Jonas", message: "Elsker denne sendingen så langt!" },
    { user: "Kari", message: "Hilsen fra Oslo!" },
    { user: "Mats", message: "Når kommer neste sending?" },
  ];
  
  export const initialComments = [
    { user: "Ole", comment: "Flott dekning!" },
    { user: "Liv", comment: "NRK leverer alltid 💙" },
  ];